---
# This may be upside down.  I think this material's only needed for wifi to ethernet.

   - name: Install parprouted
     apt:
       name: parprouted
       state: present
       update_cache: true
     tags: 
     - FW_Wifi_Eth_Br
     - bridging

   - name: Create /usr/lib/systemd/system/parprouted.service file 
     copy:
       src: "{{ root_playbook_dir }}/usr/lib/systemd/system/parprouted.service"
       dest: /usr/lib/systemd/system/parprouted.service
       owner: root
       group: root
       mode: 0744
     tags: 
     - FW_Wifi_Eth_Br
     - bridging


   - name: enable parprouted, which is used to proxy ARP while bridging
     command: systemctl enable parprouted
     tags: 
       - FW_Wifi_Eth_Br
       - bridging
     
   - name: Start parprouted.
     command: systemctl start parprouted
     tags: 
       - FW_Wifi_Eth_Br
       - bridging

   - name: Copy /etc/dhcpcd_bridging.conf file #Likely needs updates if I change interfaces
     copy:
       src: "{{ root_playbook_dir }}/etc/dhcpcd_bridging.conf"
       dest: /etc/dhcpcd.conf
       owner: root
       group: netdev
       mode: 0664
     tags: 
     - os_config_files
     - FW_Wifi_Eth_Br
     - dual_nic
     - bridging

   - name: Install conntrack
     apt:
       name: conntrack
       state: present
       update_cache: true
     tags: 
     - FW_Wifi_Eth_Br  

   - name: Copy nftables.conf file for a transparent briding firewall with no filtering
     copy:
       src: "{{ root_playbook_dir }}/etc/nftables.conf"
       dest: /etc/nftables.conf
       owner: root
       group: root
       mode: 0755
     tags: 
     - os_config_files

