---
py_version: 3.8.0
threads: 4
temp_folder: /tmp

root_playbook_dir: /home/pi/Playbooks/Transparent_Bridge_Eth_to_Wifi
os_info_path: /etc/os-release
int_count: "{{ ansible_interfaces | count }}"
ansible_python_interpreter: "/usr/bin/python3.9"
Target_Hostname: "WifiAP"
docker_host: "{{ lookup('ansible.builtin.env', 'DOCKER_HOST') }}"
ssh_password_pi: "Passw@rd"
wifi_password: "agoodsecretpassword" 
wifi_network_ssid: "workshop"
hostapd_file: "WifiRepeaterHostAPD.conf"
wifi_interface: "wlan0"
version:
  Build: WifiExtender
  BuildDate: "10_05_23"
  Ver: 0.1
  Author: p@mccannabanana.com
  Description: A Transparent Bridging wifi repeater


